### ISSUE TITLE
Change name of fields 

### ISSUE THREAD

**Issue by Giovanni-Petrella** [Pharaonic/laravel-settings#1]
Why did you change the name of the fields without doing an additional migration? this is not the case whoever had installed the extension before finds that the software no longer works

**Comment by MoamenEltouny** [comment]
hello @Giovanni-Petrella
if you mean changing `modelable` to `settingable` .. sorry for that but you can use an older version 🙏

**Comment by Giovanni-Petrella** [comment]
No problem, my software is in development I made a migration and it's fine but I said it for those who use the extension in production and do an update and find it no longer working, I just said that a migration was expected to be added directly in the extension, thanks for your great extension.
